version: 2.1
orbs:
  node: circleci/node@4.0.0

step-restore-cache: &step-restore-cache
  restore_cache:
    key: v2-sa-{{ arch }}-{{ checksum "yarn.lock" }}

step-yarn: &step-yarn
  run:
    name: Yarn Install
    command: yarn install --immutable
    environment:
      YARN_CACHE_DIR: ~/.cache/yarn
      ELECTRON_SKIP_BINARY_DOWNLOAD: 1
      SA_REPLAY_SKIP_BINARY_DOWNLOAD: 1

jobs:
  update-website:
    docker:
      - image: circleci/node:12
    executor:
      name: node/default
    steps:
      - checkout
      - *step-restore-cache
      - *step-yarn
      - add_ssh_keys:
          fingerprints:
            - '3b:86:d4:57:4f:12:0b:ad:45:49:15:d4:90:c1:51:a2'
      - run:
          name: Update site
          command: cd website && yarn deploy --message "[skip ci] Updates" --user "Circle Ci <ci@ulixee.org>"

  build-replay-mac:
    macos:
      xcode: '10.2.0'
    steps:
      - checkout
      - *step-restore-cache
      - *step-yarn
      - run:
          name: Compile Typescript and Build Electron Webpages
          command: cd ~/project/replay-app && yarn build && yarn build:icons
      - run:
          name: Yarn electron-build
          command: cd ~/project/build/replay-app && yarn && pwd && yarn electron-builder -m --publish always
      - run:
          name: Pack distributions
          command: cp ~/project/replay-app/pack.sh ~/project/build/replay-app && cd ~/project/build/replay-app && ./pack.sh
      - store_artifacts:
          path: ~/project/build/replay-app/dist/assets

  build-replay-wl:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - *step-restore-cache
      - *step-yarn
      - run:
          name: Compile Typescript and Build Electron Webpages
          command: cd ~/project/replay-app && yarn build && yarn build:icons
      - run:
          name: Yarn electron-build
          command: cd ~/project/build/replay-app && yarn && pwd && yarn electron-builder -wl --publish always
      - run:
          name: Pack distributions
          command: cp ~/project/replay-app/pack.sh ~/project/build/replay-app && cd ~/project/build/replay-app && ./pack.sh
      - store_artifacts:
          path: ~/project/build/replay-app/dist/assets

workflows:
  version: 2
  build-assets:
    jobs:
      - build-replay-wl:
          context: SecretAgent
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - build-replay-mac:
          context: SecretAgent
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
