before:
  hooks:
    - cd lib && go mod download
builds:
  - id: 'connect'
    binary: connect
    dir: ./lib
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
archives:
  - name_template: 'connect_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: mac
      linux: linux
      windows: win
      386: i386
      amd64: x86_64
    format: gz
    files:
      - none*
checksum:
  name_template: 'connect.checksum'
snapshot:
  name_template: '{{ .Tag }}-snapshot'
changelog:
  skip: true
release:
  prerelease: auto
