name: Mitm Socket

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build Sockets
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --debug
          workdir: ${{ github.workspace }}/mitm-socket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
