name: Publish Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./website/node_modules
          key: ${{ runner.os }}-website-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - name: Install Dependencies
        run: npm install
        working-directory: ./website
      - name: Build Site
        run: npm run build
        working-directory: ./website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-dist/website
          commit_message: "[skip ci] Updates"
